export const ROOM_JOIN_TRY = 'ROOM_JOIN_TRY';
export const ROOM_JOIN_CONFIRM = 'ROOM_JOIN_CONFIRM';
export const ROOM_JOIN = 'ROOM_JOIN';

export const ROOM_USER_JOINED = 'ROOM_USER_JOINED';
export const ROOM_USER_LEFT = 'ROOM_USER_LEFT';
export const ROOM_USER_UPDATE = 'ROOM_USER_UPDATE';

export const ROOM_SYNC_REQUEST = 'ROOM_sync_REQUEST';
export const ROOM_SYNC = 'ROOM_SYNC';

export const CHAT_MESSAGE_SEND = 'CHAT_MESSAGE_SEND';
export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';

export const VIDEO_LOAD_REQUEST = 'VIDEO_LOAD_REQUEST';
export const VIDEO_LOAD = 'VIDEO_LOAD';
export const VIDEO_LOAD_DONE = 'VIDEO_LOAD_DONE';

export const VIDEO_PLAY_REQUEST = 'VIDEO_PLAY_REQUEST';
export const VIDEO_PLAY = 'VIDEO_PLAY';
export const VIDEO_PLAY_DONE = 'VIDEO_PLAY_DONE';

export const VIDEO_PAUSE_REQUEST = 'VIDEO_PAUSE_REQUEST';
export const VIDEO_PAUSE = 'VIDEO_PAUSE';
export const VIDEO_PAUSE_DONE = 'VIDEO_PAUSE_DONE';

export const VIDEO_STOP_REQUEST = 'VIDEO_STOP_REQUEST';
export const VIDEO_STOP = 'VIDEO_STOP';
export const VIDEO_STOP_DONE = 'VIDEO_STOP_DONE';

export const VIDEO_BUFFER_REQUEST = 'VIDEO_BUFFERING_REQUEST';
export const VIDEO_BUFFER = 'VIDEO_BUFFERING';
export const VIDEO_BUFFER_DONE = 'VIDEO_BUFFERING_DONE';
