name: NodeJS CI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Create env file
        run: |
          touch .env
          echo SSH_HOST=164.90.172.241 >> .env
          echo SSH_USER=root >> .env
          echo SSH_KEY=~/.ssh/id_ed25519 >> .env
          echo GIT_REPOSITORY=git@github.com:rherwig/watch.git >> .env
          echo GIT_BRANCH=origin/main >> .env
          echo WEB_ROOT=/var/www/watch >> .env

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: env $(cat .env | grep -v \"#\" | xargs) npm run deploy -- --force
