name: Deployment

on:
  release:
    types: [created]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: watch.hrwg.de

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Scan known hosts
        run: ssh-keyscan -H 164.90.172.241 >> ~/.ssh/known_hosts

      - name: Create env file
        run: |
          touch .env
          echo SSH_HOST=164.90.172.241 >> .env
          echo SSH_USER=root >> .env
          echo GIT_REPOSITORY=git@github.com:rherwig/watch.git >> .env
          echo GIT_BRANCH=origin/main >> .env
          echo WEB_ROOT=/var/www/watch >> .env

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: env $(cat .env | grep -v \"#\" | xargs) npm run deploy -- --force
